ECHO Editing shader properties


color 0A

if exist ..\..\..\maps\tags.dat (
	GOTO Label0
) else (
	GOTO Label1
)

:Label0

Type reachSniperDark.cmds | TagTool.exe ../../../maps/tags.dat

ECHO Installation Complete ...
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM
ECHO TO UNINSTALL THE DARK MODIFIER, YOU MUST REINSTALL THE WHOLE MOD VIA FMM

pause
GOTO End

:Label1
ECHO WARNING Mod is not in the correct location.
ECHO Install at: /mods/tagMods/reachSniper