set /p cleanPath=Enter the clean tags.dat path.
set /p moddedPath=Enter the modded tags.dat path.
FOR %%f IN (..\scripts\autogenerated\*.cmds) DO (echo ScriptChanges %%~nf "%moddedPath%" %%~nf >> "extractScript.cmds")
Type "extractScript.cmds"| "TagTool_Compare.exe" "%cleanPath%"
del "extractScript.cmds"
FOR %%f IN (..\scripts\autogenerated\*.cmds) DO (del %%f)
FOR %%f IN (scripts\*.cmds) DO (move %%f ..\scripts\autogenerated\)
pause